version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employeedb
    networks:
      app:

  java:
    container_name: java
    image: registry.example.com/k3s/java-app:5
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
    networks:
      app:

networks:
  app:
    driver: bridge
