name: Starting jenkins CI

on:
  push:

jobs:
  build:
    runs-on: my-custom-runner
    steps:
    - name: Build the Docker image
      run: curl http://jenkins-agent.jenkins:50000/job/java-app-pipeline/build?token=jkhdsaksdhaiasouuriweurower
